### ISSUE TITLE
Retain original repo on upgrades

### ISSUE THREAD

**Issue by WesGilster** [area515/Creation-Workshop-Host#242]
At one time we had this, but it hasn't worked in quite some time. I was recently testing a feature from my dev repo when a restart caused me to revert back to the area515. I didn't realize this had happened, and about lost my mind in a remote debug session.

I thought you may have mentioned that this feature was coming back, but I just wanted to check.

**Comment by jmkao** [comment]
Yes, this is in 923e2366b24f5691feb0e9cec2bb7a5de214bb02.

If you add:

```
updateRepo=WesGilster/Creation-Workshop-Host
```

To $HOME/3dPrinters/config.properties, `start.sh` will use that listed repo by default.

Although, there is currently one flaw that I'm investigating, that this doens't work when `start.sh` is called from the service control subsystem (e.g. `service cwhservice start`). I think the problem here is that $HOME is not set to /root in this case, and so it doesn't find the config file and falls back on area515. i still need to confirm this and see what the best way to resolve it is.
